---
title: "100 Days of Version Control"
---

By completing this training, you are automatically subscribed to the 100 Days of Version Control Challenge! 🎉 

### Purpose
The purpose of this challenge is to encourage you to create the habit of committing and pushing often, and to lose the fear of version control. It is also aimed at practicing and implementing best practices related to version control, such as descriptive commit messages, rules for branching, grouping commits per push, etc.

### Outcome 
At the end of the 100 days, you will have a history of contributions that is registered on GitHub (that you can use as a portfolio!). We hope that the multiple milestones and cellebrations, and also the record of everything that you do during these 100 days will empower you to keep the habit throughout your career.

### Process
You will work in teams of three on a shared project. You can, potentially, work on more than one project as long as you collaborate on them during the 100 days. 

You will need to make contributions in the form of commits and push, PRs, or merges every day, for 100 days. 

For each challenge, you or your group will need to submit your nominations using the designated form to be provided by the organization on this page at a future date.

You will also have access to office hours every Monday at 10am PT to debug and ask questions, and you can chose to be mentored by one of the instructors during these hours.

#### Milestones
Every 30 days will mark a milestone, and a “newsletter” will be sent to all participants with highlights of the month, featuring achievements, anonymized bugs and solutions to these bugs, and what to expect for the next 30 days (reminder of the challenges).

At the end of the 100 days + one week (March 13, 2026), there will be a big celebration with distribution of prizes.

Details about online calls and graduation party will be announced here and on the monthly newsletter.

### GitHub repository for participation

All activities will be tracked on a GitHub repository. There you can find more detailed instructions about each challenge and how to record your 100 days journey.

You should have received an invite to contribute to this repository, so you'd have access to push, pull and comment on issues. If you did not get one of if your invitation has expired, let us know!

:::{.callout-important appearance="minimal"}
👉 [**https://github.com/INN-SFU/100daysofversioncontrol/**](https://github.com/INN-SFU/100daysofversioncontrol/){.external target="_blank"}
:::

## Prizes

You heard it right! There are prizes involved! Here's the complete breakdown of who gets what:

| Challenge                                     | Prizes                              |
|-----------------------------------------------|-------------------------------------|
| Complete one tier of challenges               | Sticker                             |
| Funniest commit message                       | Sticker + CAD$ 5 gift card          |
| Best branch name                              | Sticker + CAD$ 5 gift card          |
| Completes at least two tiers of challenges    | Mug + Sticker + CAD$ 10 gift card   |
| Find an easter egg                            | Mug + Sticker + CAD$ 10 gift card   |
| Contributes to a project for at least 60 days | Mug + Sticker + CAD$ 15 gift card   |
| Most descriptive commit message               | Mug + Sticker + CAD$ 15 gift card   |
| Best README                                   | Mug + Sticker + CAD$ 15 gift card   |
| Completes all three tiers of challenges       | Mug + Sticker + CAD$ 25 gift card   |
